import { WeatherProvider } from "@/context/WeatherContext";
import "./globals.css";
import { ThemeProvider } from "@/context/Theme";


export const metadata = {
  title: "Weather app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-popover">
       
        <ThemeProvider
           attribute="class" 
            defaultTheme="system"   
            >
          <WeatherProvider>{children}</WeatherProvider> 
        </ThemeProvider>
       </body>
    </html>
  );
}
